### ISSUE TITLE
Tap to vote

### ISSUE THREAD

**Issue by arunsathiya** [Kinark/winston#68] opened 2023-09-10 08:57 UTC
Feature request. It’d be nice to tap on the upvote and downvote buttons on comments. Right now, it seems that the only way to vote is to swipe.

**Comment by ojsef39** [comment] 2023-09-10 13:24
thank you for your feature request! we'll look into that.

btw you can also long press the comment to up/downvote :)

**Comment by ojsef39** [comment] 2023-09-18 13:06
The issue is currently resolved and merged to the alpha branch for testing. thx @ben-wheeler

**Closed by ojsef39** 2023-09-18 13:06 UTC
Labels: feature/enhancement

**Comment by ben-wheeler** [comment] 2023-11-11 11:46
just thought i would comment to note this got added into the latest test flight build published today 🎉
